REM INSERTING into ROLE
Insert into ROLE (ROLE_ID,NAME) values (1,'CUSTOMER');

Insert into ROLE (ROLE_ID,NAME) values (2,'ADMIN');

Insert into ROLE (ROLE_ID,NAME) values (3,'SPONSOR');

REM INSERTING admin user
Insert into ACCOUNT_STATUS (ID,IS_ACCOUNT_ENABLED,IS_ACCOUNT_EXPIRED,IS_ACCOUNT_LOCKED,IS_CREDENDIALS_EXPIRED) values (1,1,0,0,0);

Insert into ACCOUNT (ID,CONFIRMATION_CODE,FIRST_NAME,LAST_LOGIN_DATE,LAST_NAME,MODIFIED_DATE,PASSWORD,PHONE_NUMBER,REGISTRATION_DATE,USER_NAME,VERSION,ACCOUNT_STATUS) values (1,'1','Admin','Admin',null,'4b1b510b81ee696089960aa468e80ea14bacdd2a8f54eaf2fd7755aa59d2b878','000-000-0000',null,'admin',1,1);

Insert into USER_ROLE (ID,ACCOUNT_ID,ROLE_ID) values (1,1,1);

Insert into USER_ROLE (ID,ACCOUNT_ID,ROLE_ID) values (2,1,2);



REM inserting LOOKUP DATA TYPES

INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(1,0,0,"Campany Category","COMPANY_CATEGORY",0,0);
INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(2,0,0,"Campany Industry","COMPANY_INDUSTRY",0,0);
INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(3,0,0,"Funding Source","FUNDING_SOURCE",0,0);
INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(4,0,0,"Funding Type","FUNDING_TYPE",0,0);
INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(5,0,0,"Document Type","DOCUMENT_TYPE",0,0);
INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(6,0,0,"Account Type","ACCOUNT_TYPE",0,0);
INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(7,0,0,"Team Member Type","TEAM_MEMBER_TYPE",0,0);
INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(8,0,0,"Investor Type","INVESTOR_TYPE",0,0);
INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(9,0,0,"Deveopment Categories","DEVELOPMENT_CATEGORIES",1,1);
INSERT INTO LOOKUP_DATA_TYPE(ID,IS_DELETED,VERSION,DISPLAY_VALUE,NAME,HAS_IMAGE,HAS_TYPE) VALUES(10,0,0,"Deveopment Phases","DEVELOPMENT_PHASES",0,1);



